### ISSUE TITLE
really good job. need more improvment UI view.

### ISSUE THREAD

**Issue by umefarooq** [baianat/builder#2]
I really like you work, really great job, have look on this page editor its jquery based and have really nice features, it is keeping container and components on right panel drag and drop. have look on it can give you good idea. all container and components are plugin you can create own and add to it, but way of adding little complex.

https://github.com/Kademi/keditor

**Comment by logaretm** [comment]
Thanks! we still haven't decided on how the UX should work but we will probably go with something similar like keditor, since a lot of similar projects out there follow the same approach.
